services:
  api-console-andbank:
    build:
      context: ApiConsole
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION_STRING=Server=stockdb;Port=5432;Database=StockOptions;User Id=postgres;Password=postgres;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15;
    depends_on:
      - stockdb
    deploy:
      resources:
        limits:
          memory: 1024MB
          cpus: '1'

  api-rest-andbank:
    build:
      context: ApiRest
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:3000
      - ConnectionStrings__DefaultConnection=Server=stockdb;Port=5432;Database=StockOptions;User Id=postgres;Password=postgres;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15;
    ports:
       - 3000:3000
    depends_on:
      - stockdb

  stockdb:
    image: postgres:16
    environment:
      POSTGRES_DB: StockOptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
